-- STEP 12: Blood Donation
create table if not exists public.blood_donors (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 120),
  blood_group text not null check (blood_group in ('A+','A-','B+','B-','AB+','AB-','O+','O-')),
  area text not null check (char_length(area) between 1 and 150),
  mobile text not null check (char_length(mobile) between 7 and 30),
  whatsapp text check (whatsapp is null or char_length(whatsapp) between 7 and 30),
  availability boolean not null default true,
  last_donation date,
  created_at timestamptz not null default now()
);

create index if not exists blood_donors_search_idx on public.blood_donors(blood_group, area, availability);
alter table public.blood_donors enable row level security;

drop policy if exists "authenticated_read_available_donors" on public.blood_donors;
create policy "authenticated_read_available_donors" on public.blood_donors for select to authenticated using (availability = true or user_id = auth.uid());
drop policy if exists "users_insert_own_donor" on public.blood_donors;
create policy "users_insert_own_donor" on public.blood_donors for insert to authenticated with check (user_id = auth.uid());
drop policy if exists "users_update_own_donor" on public.blood_donors;
create policy "users_update_own_donor" on public.blood_donors for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
drop policy if exists "users_delete_own_donor" on public.blood_donors;
create policy "users_delete_own_donor" on public.blood_donors for delete to authenticated using (user_id = auth.uid());

create table if not exists public.blood_requests (
  id bigint generated by default as identity primary key,
  requester_id uuid references auth.users(id) on delete set null,
  patient_name text not null check (char_length(patient_name) between 1 and 120),
  blood_group text not null check (blood_group in ('A+','A-','B+','B-','AB+','AB-','O+','O-')),
  area text not null check (char_length(area) between 1 and 150),
  mobile text not null check (char_length(mobile) between 7 and 30),
  needed_date date,
  emergency boolean not null default false,
  status text not null default 'open' check (status in ('open','fulfilled','closed')),
  created_at timestamptz not null default now()
);
alter table public.blood_requests enable row level security;
drop policy if exists "authenticated_read_open_requests" on public.blood_requests;
create policy "authenticated_read_open_requests" on public.blood_requests for select to authenticated using (status = 'open' or requester_id = auth.uid() or public.is_admin());
drop policy if exists "users_create_request" on public.blood_requests;
create policy "users_create_request" on public.blood_requests for insert to authenticated with check (requester_id = auth.uid());
drop policy if exists "users_update_own_request" on public.blood_requests;
create policy "users_update_own_request" on public.blood_requests for update to authenticated using (requester_id = auth.uid() or public.is_admin()) with check (requester_id = auth.uid() or public.is_admin());
