-- STEP 10: Personal Notepad
-- Run this SQL in Supabase SQL Editor.
create table if not exists public.personal_notes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null default 'নতুন নোট' check (char_length(title) between 1 and 200),
  content text not null default '',
  is_private boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists personal_notes_user_updated_idx
  on public.personal_notes(user_id, updated_at desc);

alter table public.personal_notes enable row level security;

drop policy if exists "users_read_own_notes" on public.personal_notes;
create policy "users_read_own_notes"
  on public.personal_notes for select to authenticated
  using (user_id = auth.uid());

drop policy if exists "users_insert_own_notes" on public.personal_notes;
create policy "users_insert_own_notes"
  on public.personal_notes for insert to authenticated
  with check (user_id = auth.uid() and is_private = true);

drop policy if exists "users_update_own_notes" on public.personal_notes;
create policy "users_update_own_notes"
  on public.personal_notes for update to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid() and is_private = true);

drop policy if exists "users_delete_own_notes" on public.personal_notes;
create policy "users_delete_own_notes"
  on public.personal_notes for delete to authenticated
  using (user_id = auth.uid());

create or replace function public.set_personal_notes_updated_at()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists personal_notes_updated_at on public.personal_notes;
create trigger personal_notes_updated_at
before update on public.personal_notes
for each row execute function public.set_personal_notes_updated_at();
