-- STEP 14: Islamic Quiz history / badges
create table if not exists public.quiz_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  category text not null default 'সাধারণ ইসলামিক জ্ঞান',
  score integer not null check (score between 0 and 10),
  total integer not null default 10 check (total > 0),
  quiz_date date not null default current_date,
  created_at timestamptz not null default now()
);
alter table public.quiz_history enable row level security;
drop policy if exists "users_read_own_quiz_history" on public.quiz_history;
create policy "users_read_own_quiz_history" on public.quiz_history for select to authenticated using (user_id = auth.uid());
drop policy if exists "users_insert_own_quiz_history" on public.quiz_history;
create policy "users_insert_own_quiz_history" on public.quiz_history for insert to authenticated with check (user_id = auth.uid());
create index if not exists quiz_history_user_date_idx on public.quiz_history(user_id, created_at desc);

create table if not exists public.quiz_badges (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  badge text not null,
  awarded_at timestamptz not null default now(),
  unique(user_id,badge)
);
alter table public.quiz_badges enable row level security;
drop policy if exists "users_read_own_quiz_badges" on public.quiz_badges;
create policy "users_read_own_quiz_badges" on public.quiz_badges for select to authenticated using (user_id = auth.uid());
drop policy if exists "users_insert_own_quiz_badges" on public.quiz_badges;
create policy "users_insert_own_quiz_badges" on public.quiz_badges for insert to authenticated with check (user_id = auth.uid());
