-- STEP 11: ব্যক্তিগত রিপোর্ট বই
create table if not exists public.personal_reports (
  id bigint generated by default as identity primary key,
  member_id uuid not null references auth.users(id) on delete cascade,
  report_date date not null default current_date,
  title text not null default 'ব্যক্তিগত রিপোর্ট' check (char_length(title) between 1 and 200),
  content text not null default '',
  status text not null default 'draft' check (status in ('draft','submitted','approved')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists personal_reports_member_date_idx
  on public.personal_reports(member_id, report_date desc, updated_at desc);

alter table public.personal_reports enable row level security;

drop policy if exists "members_read_own_reports" on public.personal_reports;
create policy "members_read_own_reports" on public.personal_reports
for select to authenticated using (member_id = auth.uid());

drop policy if exists "members_insert_own_reports" on public.personal_reports;
create policy "members_insert_own_reports" on public.personal_reports
for insert to authenticated with check (member_id = auth.uid());

drop policy if exists "members_update_own_reports" on public.personal_reports;
create policy "members_update_own_reports" on public.personal_reports
for update to authenticated using (member_id = auth.uid()) with check (member_id = auth.uid());

drop policy if exists "members_delete_own_reports" on public.personal_reports;
create policy "members_delete_own_reports" on public.personal_reports
for delete to authenticated using (member_id = auth.uid());

-- Admin access. A future দায়িত্বশীল role can be added to profiles after its exact scope is defined.
drop policy if exists "admins_read_reports" on public.personal_reports;
create policy "admins_read_reports" on public.personal_reports
for select to authenticated using (public.is_admin());

drop policy if exists "admins_update_reports" on public.personal_reports;
create policy "admins_update_reports" on public.personal_reports
for update to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "admins_delete_reports" on public.personal_reports;
create policy "admins_delete_reports" on public.personal_reports
for delete to authenticated using (public.is_admin());

create or replace function public.set_personal_reports_updated_at()
returns trigger language plpgsql security definer set search_path = public
as $$
begin new.updated_at = now(); return new; end;
$$;

drop trigger if exists personal_reports_updated_at on public.personal_reports;
create trigger personal_reports_updated_at before update on public.personal_reports
for each row execute function public.set_personal_reports_updated_at();
