-- STEP 22: Advanced Security baseline
-- Run after reviewing existing schema. This script creates an append-only audit log
-- and tightens access to personal/member data.
create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  action text not null,
  resource text,
  resource_id text,
  created_at timestamptz not null default now()
);
alter table public.audit_log enable row level security;

drop policy if exists "users_read_own_audit" on public.audit_log;
create policy "users_read_own_audit" on public.audit_log
for select to authenticated using (user_id = auth.uid());

-- Only the authenticated user can insert an audit event for their own user id.
drop policy if exists "users_insert_own_audit" on public.audit_log;
create policy "users_insert_own_audit" on public.audit_log
for insert to authenticated with check (user_id = auth.uid());

-- No client-side update/delete policies are intentionally provided.

-- Personal notes: keep access owner-only when this table exists.
-- Personal reports: keep access owner-only; privileged admin/responsible access
-- should be implemented through server-side/RPC authorization, not client filters.
-- Phone numbers and blood-donation contact data should only be exposed when
-- the corresponding privacy permission is true.
