/* SOHOCHOR Locale Bridge v2 */
(function(){
'use strict';
const rtl=['ar','ur','fa','he'];
const MAP={BD:'bn',IN:'hi',PK:'ur',SA:'ar',AE:'ar',QA:'ar',KW:'ar',BH:'ar',OM:'ar',YE:'ar',JO:'ar',IQ:'ar',EG:'ar',MA:'ar',DZ:'ar',TN:'ar',TR:'tr',ID:'id',MY:'ms',IR:'fa',AF:'fa',CN:'zh',TW:'zh',JP:'ja',KR:'ko',ES:'es',FR:'fr',DE:'de',PT:'pt',BR:'pt',RU:'ru',IT:'it',NL:'nl',PL:'pl',SE:'sv',NO:'no',DK:'da',FI:'fi',GR:'el',IL:'he',TH:'th',VN:'vi',UA:'uk',RO:'ro',HU:'hu',CZ:'cs',SK:'sk',BG:'bg',RS:'sr',HR:'hr',BA:'bs',AL:'sq',AZ:'az',KZ:'kk',UZ:'uz',TJ:'tg',TM:'tk',KG:'ky'};
const L=[['bn','বাংলা'],['en','English'],['ar','العربية'],['hi','हिन्दी'],['ur','اردو'],['ms','Bahasa Melayu'],['fa','فارسی'],['tr','Türkçe'],['id','Bahasa Indonesia'],['es','Español'],['fr','Français'],['de','Deutsch'],['pt','Português'],['ru','Русский'],['zh','中文'],['ja','日本語'],['ko','한국어'],['it','Italiano'],['nl','Nederlands'],['pl','Polski'],['sv','Svenska'],['no','Norsk'],['da','Dansk'],['fi','Suomi'],['el','Ελληνικά'],['he','עברית'],['sw','Kiswahili'],['ta','தமிழ்'],['te','తెలుగు'],['ml','മലയാളം'],['kn','ಕನ್ನಡ'],['mr','मराठी'],['gu','ગુજરાતી'],['pa','ਪੰਜਾਬੀ'],['ne','नेपाली'],['si','සිංහල'],['th','ไทย'],['vi','Tiếng Việt'],['uk','Українська'],['ro','Română'],['hu','Magyar'],['cs','Čeština'],['sk','Slovenčina'],['bg','Български'],['sr','Српски'],['hr','Hrvatski'],['bs','Bosanski'],['sq','Shqip'],['az','Azərbaycan'],['kk','Қазақша'],['uz','O‘zbekcha'],['tg','Тоҷикӣ'],['tk','Türkmençe'],['ky','Кыргызча']];
function setCookie(v){document.cookie='googtrans='+v+';path=/;SameSite=Lax';if(location.hostname)document.cookie='googtrans='+v+';path=/;domain='+location.hostname+';SameSite=Lax'}
function clear(){document.cookie='googtrans=;expires=Thu, 01 Jan 1970 00:00:00 GMT;path=/';if(location.hostname)document.cookie='googtrans=;expires=Thu, 01 Jan 1970 00:00:00 GMT;path=/;domain='+location.hostname}
function choose(l){localStorage.setItem('sohochorLanguage',l);document.documentElement.dir=rtl.includes(l)?'rtl':'ltr';if(l==='bn'){clear();location.reload();return}setCookie('/bn/'+l);const s=document.querySelector('#google_translate_element select.goog-te-combo');if(s){s.value=l;s.dispatchEvent(new Event('change'));return}location.reload()}
function hook(){document.querySelectorAll('#sohochor-language,.sl-select:nth-child(2)').forEach(s=>{if(!s.__locale){s.__locale=true;s.addEventListener('change',()=>choose(s.value))}});document.querySelectorAll('#sohochor-country-language .sl-language-menu button').forEach(b=>{if(!b.__locale){b.__locale=true;b.addEventListener('click',()=>choose(b.dataset.value),true)}});document.querySelectorAll('.sl-status').forEach(x=>x.style.display='none')}
function load(){if(document.getElementById('sohochor-global-gt'))return;const h=document.createElement('div');h.id='google_translate_element';h.className='notranslate';h.style.cssText='position:fixed;left:-9999px;top:-9999px;width:1px;height:1px;overflow:hidden';document.body.appendChild(h);window.googleTranslateElementInit=function(){try{new google.translate.TranslateElement({pageLanguage:'bn',includedLanguages:L.map(x=>x[0]).join(','),autoDisplay:false,multilanguagePage:true},'google_translate_element')}catch(e){}};const s=document.createElement('script');s.id='sohochor-global-gt';s.src='https://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit';s.async=true;document.head.appendChild(s)}
function start(){hook();const l=localStorage.getItem('sohochorLanguage')||MAP[localStorage.getItem('sohochorCountry')||'BD']||'bn';document.documentElement.dir=rtl.includes(l)?'rtl':'ltr';if(l!=='bn'){setCookie('/bn/'+l);load();setTimeout(()=>{const s=document.querySelector('#google_translate_element select.goog-te-combo');if(s){s.value=l;s.dispatchEvent(new Event('change'))}},1200)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();setTimeout(hook,700);
})();