/* SOHOCHOR Global Locale v1 — full-site language bridge */
(function(){
'use strict';
const LANGS=[['bn','বাংলা'],['en','English'],['ar','العربية'],['hi','हिन्दी'],['ur','اردو'],['ms','Bahasa Melayu'],['fa','فارسی'],['tr','Türkçe'],['id','Bahasa Indonesia'],['es','Español'],['fr','Français'],['de','Deutsch'],['pt','Português'],['ru','Русский'],['zh','中文'],['ja','日本語'],['ko','한국어'],['it','Italiano'],['nl','Nederlands'],['pl','Polski'],['sv','Svenska'],['no','Norsk'],['da','Dansk'],['fi','Suomi'],['el','Ελληνικά'],['he','עברית'],['sw','Kiswahili'],['ta','தமிழ்'],['te','తెలుగు'],['ml','മലയാളം'],['kn','ಕನ್ನಡ'],['mr','मराठी'],['gu','ગુજરાતી'],['pa','ਪੰਜਾਬੀ'],['ne','नेपाली'],['si','සිංහල'],['th','ไทย'],['vi','Tiếng Việt'],['uk','Українська'],['ro','Română'],['hu','Magyar'],['cs','Čeština'],['sk','Slovenčina'],['bg','Български'],['sr','Српски'],['hr','Hrvatski'],['bs','Bosanski'],['sq','Shqip'],['az','Azərbaycan'],['kk','Қазақша'],['uz','O‘zbekcha'],['tg','Тоҷикӣ'],['tk','Türkmençe'],['ky','Кыргызча']];
const MAP={BD:'bn',IN:'hi',PK:'ur',SA:'ar',AE:'ar',QA:'ar',KW:'ar',BH:'ar',OM:'ar',YE:'ar',JO:'ar',IQ:'ar',EG:'ar',MA:'ar',DZ:'ar',TN:'ar',TR:'tr',ID:'id',MY:'ms',IR:'fa',AF:'fa',CN:'zh',TW:'zh',JP:'ja',KR:'ko',ES:'es',FR:'fr',DE:'de',PT:'pt',BR:'pt',RU:'ru',IT:'it',NL:'nl',PL:'pl',SE:'sv',NO:'no',DK:'da',FI:'fi',GR:'el',IL:'he',TH:'th',VN:'vi',UA:'uk',RO:'ro',HU:'hu',CZ:'cs',SK:'sk',BG:'bg',RS:'sr',HR:'hr',BA:'bs',AL:'sq',AZ:'az',KZ:'kk',UZ:'uz',TJ:'tg',TM:'tk',KG:'ky'};
function cookie(n,v){document.cookie=n+'='+v+';path=/;SameSite=Lax';if(location.hostname)document.cookie=n+'='+v+';path=/;domain='+location.hostname+';SameSite=Lax'}
function clearCookie(n){document.cookie=n+'=;expires=Thu, 01 Jan 1970 00:00:00 GMT;path=/';if(location.hostname)document.cookie=n+'=;expires=Thu, 01 Jan 1970 00:00:00 GMT;path=/;domain='+location.hostname}
function lang(){return localStorage.getItem('sohochorLanguage')||MAP[localStorage.getItem('sohochorCountry')||'BD']||'bn'}
function googleReady(){return !!document.querySelector('#google_translate_element select.goog-te-combo')}
function selectGoogle(l){const s=document.querySelector('#google_translate_element select.goog-te-combo');if(s){s.value=l;s.dispatchEvent(new Event('change'));return true}return false}
function loadGoogle(){if(document.getElementById('sohochor-google-script'))return;const h=document.createElement('div');h.id='google_translate_element';h.className='notranslate';h.style.cssText='position:fixed;left:-10000px;top:-10000px;width:1px;height:1px;overflow:hidden';document.body.appendChild(h);window.googleTranslateElementInit=function(){try{new google.translate.TranslateElement({pageLanguage:'bn',includedLanguages:LANGS.map(x=>x[0]).join(','),autoDisplay:false,multilanguagePage:true},'google_translate_element')}catch(e){}};const s=document.createElement('script');s.id='sohochor-google-script';s.src='https://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit';s.async=true;document.head.appendChild(s)}
function choose(l){localStorage.setItem('sohochorLanguage',l);cookie('googtrans','/bn/'+l);document.documentElement.lang='bn';if(l==='bn'){clearCookie('googtrans');location.reload()}else if(!selectGoogle(l)){loadGoogle();setTimeout(()=>selectGoogle(l),1000);setTimeout(()=>{if(!googleReady())location.reload()},1600)}}
function createPicker(){if(document.getElementById('sohochor-global-locale')||document.getElementById('sohochor-country-language'))return;const box=document.createElement('div');box.id='sohochor-global-locale';box.className='notranslate';box.innerHTML='<button type="button" class="gl-locale" aria-label="Language">🌐 <span>Language</span>⌄</button><div class="gl-menu"></div>';const menu=box.querySelector('.gl-menu');LANGS.forEach(x=>{const b=document.createElement('button');b.type='button';b.dataset.lang=x[0];b.textContent=x[1];menu.appendChild(b);b.onclick=()=>choose(x[0])});const host=document.querySelector('.nav .nav-actions')||document.querySelector('header .nav')||document.querySelector('header')||document.body;host.prepend(box);const btn=box.querySelector('.gl-locale');btn.onclick=e=>{e.stopPropagation();menu.classList.toggle('open')};document.addEventListener('click',()=>menu.classList.remove('open'))}
function hookExisting(){document.querySelectorAll('#sohochor-country-language .sl-language-menu button').forEach(b=>{if(!b.__glHook){b.__glHook=true;b.addEventListener('click',()=>choose(b.dataset.value),true)}})}
function css(){if(document.getElementById('sohochor-global-locale-css'))return;const s=document.createElement('style');s.id='sohochor-global-locale-css';s.textContent='#sohochor-global-locale{position:relative;margin:0 4px;z-index:10000}#sohochor-global-locale .gl-locale{height:36px;border:1px solid rgba(255,255,255,.28);border-radius:12px;background:linear-gradient(135deg,#138b58,#075d3b);color:#fff;padding:0 11px;font:800 12px system-ui;box-shadow:0 5px 14px #0002;cursor:pointer}#sohochor-global-locale .gl-menu{display:none;position:absolute;right:0;top:42px;width:190px;max-height:330px;overflow:auto;background:#fff;border:1px solid #d8e7df;border-radius:14px;padding:6px;box-shadow:0 18px 40px #0003}#sohochor-global-locale .gl-menu.open{display:block}#sohochor-global-locale .gl-menu button{display:block;width:100%;border:0;background:#fff;text-align:left;border-radius:9px;padding:9px;color:#17382b;font:700 12px system-ui}#sohochor-global-locale .gl-menu button:hover{background:#edf8f2}@media(max-width:700px){#sohochor-global-locale .gl-locale{height:32px;font-size:10px;padding:0 8px}}.goog-te-banner-frame,.skiptranslate{display:none!important}body{top:0!important}';document.head.appendChild(s)}
function start(){css();createPicker();hookExisting();const l=lang();if(l!=='bn'||document.cookie.indexOf('googtrans=')>=0)loadGoogle();document.documentElement.lang='bn';document.documentElement.dir=['ar','ur','fa','he'].includes(l)?'rtl':'ltr';setTimeout(()=>{if(l!=='bn')selectGoogle(l)},1200)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();