const PUSH_PUBLIC_KEY = "BC1FvK-ER2a0uXro8S_JuUsAzSBQ0dxrZqEM1kox8s7l1C5J_AY0SYaV5UkhE8SMR-opBgrYey8w0i0dazs9eKQ";
function pushSupported(){return "serviceWorker" in navigator&&"PushManager" in window&&"Notification" in window}
function urlBase64ToUint8Array(base64String){const padding="=".repeat((4-base64String.length%4)%4);const base64=(base64String+padding).replace(/-/g,"+").replace(/_/g,"/");return Uint8Array.from([...atob(base64)].map(c=>c.charCodeAt(0)))}
async function supabasePushClient(){const db=window.db||window.supabase?.createClient?.("https://pgwxfccpphjjveoeeqhv.supabase.co","sb_publishable_Hi2YfMYdGfGS3al-ojQA9A_6wPEG2ym");if(!db)throw new Error("Supabase client not available");return db}
async function registerPushSubscription(showFeedback=true){if(!pushSupported())throw new Error("এই ব্রাউজারে Push Notification সমর্থিত নয়।");const permission=await Notification.requestPermission();if(permission!=="granted")throw new Error("Notification permission অনুমোদন করা হয়নি।");const registration=await navigator.serviceWorker.ready;let subscription=await registration.pushManager.getSubscription();if(!subscription)subscription=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:urlBase64ToUint8Array(PUSH_PUBLIC_KEY)});const db=await supabasePushClient();const {data:{user}}=await db.auth.getUser();const payload=subscription.toJSON();if(!payload.endpoint||!payload.keys?.p256dh||!payload.keys?.auth)throw new Error("Push subscription তৈরি করা যায়নি।");const row={user_id:user?.id||null,endpoint:payload.endpoint,p256dh:payload.keys.p256dh,auth:payload.keys.auth,user_agent:navigator.userAgent,updated_at:new Date().toISOString()};let error;if(user)({error}=await db.from("push_subscriptions").upsert(row,{onConflict:"endpoint"}));else{({error}=await db.from("push_subscriptions").insert(row));if(error?.code==="23505")error=null}if(error)throw error;if(showFeedback)alert("🔔 Notification চালু হয়েছে। নতুন News/Notice প্রকাশ হলে জানানো হবে।");return subscription}
async function installPushUI(){if(!pushSupported())return;const registration=await navigator.serviceWorker.ready;const active=!!(await registration.pushManager.getSubscription());const old=document.getElementById("pushTools");if(old)old.remove();const box=document.createElement("div");box.id="pushTools";box.className="panel";box.innerHTML=`<div class="section-title"><h2>🔔 নোটিফিকেশন</h2></div><p class="muted">নতুন নিউজ ও নোটিশ প্রকাশ হলে আপনার ফোনে নোটিফিকেশন পেতে চালু করুন।</p><button id="pushEnable" class="primary" type="button">${active?"🔔 Notification চালু আছে":"🔔 Notification চালু করুন"}</button>`;const main=document.querySelector("main.page")||document.body;main.insertBefore(box,main.firstChild?.nextSibling||main.firstChild);const btn=document.getElementById("pushEnable");btn.disabled=active;btn.onclick=async()=>{btn.disabled=true;try{await registerPushSubscription(true);btn.textContent="🔔 Notification চালু আছে"}catch(e){btn.disabled=false;alert(e.message||"Notification চালু করা যায়নি।")}}}
function installReminderHomeLink(){if(!location.pathname.endsWith('/index.html')&&!location.pathname.endsWith('/'))return;document.querySelectorAll('[data-coming="Alarm"],[data-coming="Reminder"]').forEach(a=>{a.removeAttribute('data-coming');a.classList.remove('coming');a.setAttribute('href','./reminder.html');const small=a.querySelector('small');if(small)small.textContent='Reminder + Alarm চালু আছে'})}
function install3DHomeLogin(){const style=document.createElement('style');style.id='sohochor-3d-buttons';style.textContent=`
:root{--s3dshadow:rgba(0,48,30,.30)}
.links a,.login,.head>a,.dark-btn,.quick a,.badge,.cta,.primary,button,.arr,.bottom a{position:relative;overflow:hidden;transition:transform .18s ease,box-shadow .18s ease,filter .18s ease!important}
.links a,.login,.head>a,.dark-btn,.cta,.primary,button{border:1px solid rgba(255,255,255,.30)!important;border-radius:13px!important;box-shadow:inset 2px 2px 5px rgba(255,255,255,.40),inset -2px -3px 6px rgba(0,0,0,.14),0 5px 0 var(--s3dshadow),0 11px 20px rgba(0,50,32,.16)!important;font-weight:900!important}
.links a[href="index.html"],.login{background:linear-gradient(145deg,#19aa6c,#075b3a 74%)!important;color:#fff!important;text-shadow:0 1px 2px #001b1066}.links a[href="index.html"]{display:inline-flex;align-items:center;justify-content:center;min-width:68px;padding:8px 13px}.login{display:inline-flex!important;align-items:center;justify-content:center;min-width:84px;padding:10px 17px!important;transform:perspective(220px) rotateX(2deg) translateY(-2px)}.links a:not([href="index.html"]){padding:8px 11px}.head>a{background:linear-gradient(145deg,#f5fff9,#d9f1e5)!important;color:#087b4c!important;padding:10px 15px}.badge{background:linear-gradient(145deg,#fff,#e9f4ef)!important;border:1px solid #d9e6df!important;border-radius:16px!important;box-shadow:inset 2px 2px 5px #fff,inset -2px -3px 5px #0000000c,4px 7px 13px #214c3a20!important}.cta,.dark-btn,.primary,button{background:linear-gradient(145deg,#ffffff,#e4f1eb);color:#075d3b}.dark-btn{box-shadow:inset 2px 2px 5px #fff,inset -2px -3px 5px #0002,0 5px 0 #022f2055,0 10px 18px #001b1038!important}.quick a{border:1px solid #dbe9e1!important;border-radius:13px!important;background:linear-gradient(145deg,#fff,#edf7f2)!important;box-shadow:inset 2px 2px 4px #fff,inset -2px -2px 4px #0001,0 4px 0 #00462d18,0 9px 15px #003c2812!important;font-weight:850}.arr{box-shadow:inset 2px 2px 4px #fff,inset -2px -2px 4px #0001,0 3px 0 #00462d18,0 6px 10px #003c2812!important}
.card{box-shadow:inset 3px 3px 8px rgba(255,255,255,.95),inset -4px -5px 10px rgba(18,55,42,.08),7px 12px 22px rgba(23,61,44,.20)!important;transition:transform .2s ease,box-shadow .2s ease,filter .2s ease!important;transform:perspective(900px) rotateX(.5deg)}
.card:before{content:"";position:absolute;inset:0 auto auto 0;width:65%;height:55%;border-radius:18px;background:linear-gradient(125deg,rgba(255,255,255,.60),transparent 62%);pointer-events:none;z-index:0}
.card .ico,.card b,.card small,.card .arr{position:relative;z-index:1}.ico,.logo3d{box-shadow:inset 2px 2px 5px #fff,inset -3px -3px 6px #0002,5px 8px 15px #173d2c24!important}.card .ico{transform:perspective(500px) translateZ(8px);box-shadow:inset 3px 3px 6px rgba(255,255,255,.95),inset -3px -4px 7px rgba(0,0,0,.12),6px 9px 16px rgba(33,76,58,.20)!important}.card .arr{box-shadow:inset 2px 2px 4px #fff,inset -2px -2px 4px #0001,0 3px 0 #00462d18,0 6px 10px #003c2812!important}
#services .card:nth-child(1){background:linear-gradient(145deg,#f4fbff,#d8edff)!important;border-color:#a9d3f2!important}.card:nth-child(1) .ico{background:linear-gradient(145deg,#e9f7ff,#b9def8)!important}.card:nth-child(1) .arr{background:#d5ebff!important;color:#14679c!important}
#services .card:nth-child(2){background:linear-gradient(145deg,#fbf4ff,#e7d5ff)!important;border-color:#d1b2ec!important}.card:nth-child(2) .ico{background:linear-gradient(145deg,#f3e8ff,#d5b8f2)!important}.card:nth-child(2) .arr{background:#ead8ff!important;color:#7541a5!important}
#services .card:nth-child(3){background:linear-gradient(145deg,#fff6f6,#ffdcdc)!important;border-color:#efb3b3!important}.card:nth-child(3) .ico{background:linear-gradient(145deg,#ffefef,#ffc5c5)!important}.card:nth-child(3) .arr{background:#ffd6d6!important;color:#b12d2d!important}
#services .card:nth-child(4){background:linear-gradient(145deg,#fff9ed,#ffe3b5)!important;border-color:#ebc78b!important}.card:nth-child(4) .ico{background:linear-gradient(145deg,#fff3d9,#ffd083)!important}.card:nth-child(4) .arr{background:#ffdfaa!important;color:#a55b12!important}
#services .card:nth-child(5){background:linear-gradient(145deg,#effbff,#d2efff)!important;border-color:#a9d6e8!important}.card:nth-child(5) .ico{background:linear-gradient(145deg,#e2f8ff,#b9e2f5)!important}.card:nth-child(5) .arr{background:#d0edff!important;color:#17719b!important}
#services .card:nth-child(6){background:linear-gradient(145deg,#fffdf0,#ffefb8)!important;border-color:#e5d28c!important}.card:nth-child(6) .ico{background:linear-gradient(145deg,#fff8d9,#ffe58d)!important}.card:nth-child(6) .arr{background:#ffebb0!important;color:#9a7412!important}
#services .card:nth-child(7){background:linear-gradient(145deg,#faf4ff,#e3d5ff)!important;border-color:#cdb6ec!important}.card:nth-child(7) .ico{background:linear-gradient(145deg,#f2e9ff,#d5bdf3)!important}.card:nth-child(7) .arr{background:#e7d9ff!important;color:#7040a0!important}
#services .card:nth-child(8){background:linear-gradient(145deg,#f0fff5,#d0f0dc)!important;border-color:#acd9bb!important}.card:nth-child(8) .ico{background:linear-gradient(145deg,#e1fae9,#b9e5c9)!important}.card:nth-child(8) .arr{background:#cef0da!important;color:#28754b!important}
.bottom a{padding:7px 4px;border-radius:13px}.bottom a.active{background:linear-gradient(145deg,#f3fff9,#d9f1e5);box-shadow:inset 2px 2px 4px #fff,inset -2px -2px 4px #0001,0 4px 0 #087b4c18,3px 7px 11px #087b4c20!important}
.links a:hover,.login:hover,.head>a:hover,.dark-btn:hover,.quick a:hover,.badge:hover,.cta:hover,.primary:hover,button:hover,.bottom a:hover,.arr:hover{transform:translateY(-4px)!important;filter:saturate(1.08) brightness(1.03)}.card:hover{transform:perspective(900px) translateY(-8px) rotateX(2deg) rotateY(-.5deg)!important;filter:saturate(1.05);box-shadow:inset 3px 3px 8px rgba(255,255,255,.98),inset -4px -5px 10px rgba(18,55,42,.10),10px 20px 34px rgba(23,61,44,.30)!important}.links a:active,.login:active,.head>a:active,.dark-btn:active,.quick a:active,.badge:active,.cta:active,.primary:active,button:active,.bottom a:active,.arr:active{transform:translateY(3px)!important;box-shadow:inset 3px 3px 7px rgba(0,0,0,.20),0 2px 0 rgba(0,48,30,.34)!important}.card:active{transform:perspective(900px) translateY(2px) rotateX(1deg)!important;box-shadow:inset 4px 4px 10px rgba(0,0,0,.12),0 2px 0 rgba(0,48,30,.18)!important}
@media(max-width:850px){.links a{display:none!important}.login{min-width:84px;padding:10px 16px!important}.bottom a{display:block!important}}@media(max-width:520px){.card{min-height:150px;border-radius:20px}.card:before{border-radius:20px}.card .ico{transform:perspective(500px) translateZ(6px)}}
`;document.head.appendChild(style)}
function loadSohochorFeatureScripts(){["./country-language.js","./zikr-counter.js","./target-lock.js"].forEach(src=>{if(!document.querySelector(`script[src="${src}"]`)){const s=document.createElement("script");s.src=src;s.defer=true;document.head.appendChild(s)}})}
document.addEventListener("DOMContentLoaded",()=>{loadSohochorFeatureScripts();installReminderHomeLink();install3DHomeLogin();navigator.serviceWorker?.register("./sw.js").then(()=>installPushUI()).catch(()=>{})});